#! /bin/sh -x

# This script is intended for use by developers only; it (re)generates
# all the autoconf/automake derived files from scratch.  Use it to
# bootstrap a Geomview tree that has been checked out using CVS, or to
# reconfigure a tree from scratch.

#
# usage:
#
#    reconf [-n]
#
#      -n means don't actually run 'configure' --- just do everything
#         up to but not including running it

if test "$1" = "-n" ; then
  configure="no"
fi

# clear out configure's cache
rm -f config.cache

# create aclocal.m4, which has our local macros from m4 subdir
# plus any automake macros from the system
aclocal -I m4

# create 'configure' from 'configure.in'
autoconf

# make sure the following files are present
# touch README AUTHORS NEWS ChangeLog

# generate config.h.in by reading acconfig.h and configure.in
autoheader

# generate Makefile.in's
automake -a

if test "$configure" != "no" ; then
  # configure (you might need to edit this for your local system)
  ./configure --with-motif=/usr/local/openmotif
fi
