/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/mbp/geomview-git/geomview-cvs/geomview/src/lib/oogl/wa/Attic/wa.lex.c,v 1.3 2003/09/10 21:27:53 rotdrop Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>
#include <unistd.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define wafsaconst const
#else
#define wafsaconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN wafsa_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((wafsa_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE wafsarestart( wafsain )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct wafsa_buffer_state *YY_BUFFER_STATE;

extern int wafsaleng;
extern FILE *wafsain, *wafsaout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		wafsaless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the wafsaless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define wafsaless(n) \
	do \
		{ \
		/* Undo effects of setting up wafsatext. */ \
		*wafsa_cp = wafsa_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		wafsa_c_buf_p = wafsa_cp = wafsa_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up wafsatext again */ \
		} \
	while ( 0 )

#define unput(c) wafsaunput( c, wafsatext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int wafsa_size_t;


struct wafsa_buffer_state
	{
	FILE *wafsa_input_file;

	char *wafsa_ch_buf;		/* input buffer */
	char *wafsa_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	wafsa_size_t wafsa_buf_size;

	/* Number of characters read into wafsa_ch_buf, not including EOB
	 * characters.
	 */
	int wafsa_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int wafsa_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int wafsa_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int wafsa_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int wafsa_fill_buffer;

	int wafsa_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via wafsarestart()), so that the user can continue scanning by
	 * just pointing wafsain at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE wafsa_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER wafsa_current_buffer


/* wafsa_hold_char holds the character lost when wafsatext is formed. */
static char wafsa_hold_char;

static int wafsa_n_chars;		/* number of characters read into wafsa_ch_buf */


int wafsaleng;

/* Points to current character in buffer. */
static char *wafsa_c_buf_p = (char *) 0;
static int wafsa_init = 1;		/* whether we need to initialize */
static int wafsa_start = 0;	/* start state number */

/* Flag which is used to allow wafsawrap()'s to do buffer switches
 * instead of setting up a fresh wafsain.  A bit of a hack ...
 */
static int wafsa_did_buffer_switch_on_eof;

void wafsarestart YY_PROTO(( FILE *input_file ));

void wafsa_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void wafsa_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE wafsa_create_buffer YY_PROTO(( FILE *file, int size ));
void wafsa_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void wafsa_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void wafsa_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER wafsa_flush_buffer( wafsa_current_buffer )

YY_BUFFER_STATE wafsa_scan_buffer YY_PROTO(( char *base, wafsa_size_t size ));
YY_BUFFER_STATE wafsa_scan_string YY_PROTO(( wafsaconst char *wafsa_str ));
YY_BUFFER_STATE wafsa_scan_bytes YY_PROTO(( wafsaconst char *bytes, int len ));

static void *wafsa_flex_alloc YY_PROTO(( wafsa_size_t ));
static void *wafsa_flex_realloc YY_PROTO(( void *, wafsa_size_t ));
static void wafsa_flex_free YY_PROTO(( void * ));

#define wafsa_new_buffer wafsa_create_buffer

#define wafsa_set_interactive(is_interactive) \
	{ \
	if ( ! wafsa_current_buffer ) \
		wafsa_current_buffer = wafsa_create_buffer( wafsain, YY_BUF_SIZE ); \
	wafsa_current_buffer->wafsa_is_interactive = is_interactive; \
	}

#define wafsa_set_bol(at_bol) \
	{ \
	if ( ! wafsa_current_buffer ) \
		wafsa_current_buffer = wafsa_create_buffer( wafsain, YY_BUF_SIZE ); \
	wafsa_current_buffer->wafsa_at_bol = at_bol; \
	}

#define YY_AT_BOL() (wafsa_current_buffer->wafsa_at_bol)

typedef unsigned char YY_CHAR;
FILE *wafsain = (FILE *) 0, *wafsaout = (FILE *) 0;
typedef int wafsa_state_type;
extern char *wafsatext;
#define wafsatext_ptr wafsatext

static wafsa_state_type wafsa_get_previous_state YY_PROTO(( void ));
static wafsa_state_type wafsa_try_NUL_trans YY_PROTO(( wafsa_state_type current_state ));
static int wafsa_get_next_buffer YY_PROTO(( void ));
static void wafsa_fatal_error YY_PROTO(( wafsaconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up wafsatext.
 */
#define YY_DO_BEFORE_ACTION \
	wafsatext_ptr = wafsa_bp; \
	wafsaleng = (int) (wafsa_cp - wafsa_bp); \
	wafsa_hold_char = *wafsa_cp; \
	*wafsa_cp = '\0'; \
	wafsa_c_buf_p = wafsa_cp;

#define YY_NUM_RULES 26
#define YY_END_OF_BUFFER 27
static wafsaconst short int wafsa_accept[91] =
    {   0,
        0,    0,   27,   25,    1,   20,   17,   18,   25,    1,
       23,   22,   19,   21,   25,   25,   25,   25,   25,   25,
       25,   25,   15,   16,   25,    1,   23,   22,    1,   23,
       23,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   23,   25,   25,   25,    7,   25,    4,   14,
        8,   25,   25,   25,   24,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   11,
       25,   25,   25,    2,   25,   12,    3,   25,    5,   25,
       25,   25,   25,    6,   25,   10,   13,   25,    9,    0
    } ;

static wafsaconst int wafsa_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    1,    1,    3,    1,    1,    4,
        5,    1,    6,    7,    6,    8,    1,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    1,   10,    1,
       11,    1,    1,    1,    1,    1,    1,    1,    1,   12,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,   13,   14,    1,    1,

       15,   16,    1,   17,   18,    1,    1,   19,   20,   21,
       22,   23,    1,   24,   25,   26,    1,   27,    1,    1,
       28,    1,   29,    1,   30,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static wafsaconst int wafsa_meta[31] =
    {   0,
        1,    2,    2,    2,    2,    1,    1,    1,    1,    2,
        2,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    2
    } ;

static wafsaconst short int wafsa_base[92] =
    {   0,
        0,    0,  107,    0,   29,  108,  108,  108,   24,   32,
       97,   29,  108,  108,   83,   16,   88,   18,   82,   84,
       18,   88,  108,  108,    0,   43,   91,   39,   47,    0,
       90,   74,   74,   83,   70,   70,   80,   65,   70,   77,
       69,   64,   78,   66,   68,   70,    0,   63,    0,   67,
        0,   27,   67,   62,   70,   65,   64,   57,   62,   50,
       47,   57,   49,   57,   43,   54,   52,   40,   40,    0,
       39,   44,   48,    0,   46,    0,    0,   45,    0,   34,
       39,   31,   31,    0,   40,    0,    0,   27,    0,  108,
       40

    } ;

static wafsaconst short int wafsa_def[92] =
    {   0,
       90,    1,   90,   91,   90,   90,   90,   90,   91,   91,
       91,   91,   90,   90,   91,   91,   91,   91,   91,   91,
       91,   91,   90,   90,   91,   90,   91,   91,   91,   91,
       91,   91,   91,   91,   91,   91,   91,   91,   91,   91,
       91,   91,   91,   91,   91,   91,   91,   91,   91,   91,
       91,   91,   91,   91,   91,   91,   91,   91,   91,   91,
       91,   91,   91,   91,   91,   91,   91,   91,   91,   91,
       91,   91,   91,   91,   91,   91,   91,   91,   91,   91,
       91,   91,   91,   91,   91,   91,   91,   91,   91,    0,
       90

    } ;

static wafsaconst short int wafsa_nxt[139] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,    4,   18,    4,   19,    4,   20,
        4,    4,    4,    4,   21,    4,   22,    4,   23,   24,
       26,   27,   28,   26,   33,   26,   31,   28,   29,   36,
       25,   34,   37,   40,   26,   41,   31,   28,   26,   26,
       61,   89,   62,   29,   88,   87,   86,   85,   84,   83,
       82,   81,   80,   79,   78,   77,   76,   75,   74,   73,
       72,   71,   70,   69,   68,   67,   66,   65,   55,   64,
       63,   60,   59,   58,   57,   56,   55,   54,   53,   52,
       51,   50,   49,   48,   47,   46,   45,   44,   43,   30,

       42,   39,   38,   35,   32,   30,   90,    3,   90,   90,
       90,   90,   90,   90,   90,   90,   90,   90,   90,   90,
       90,   90,   90,   90,   90,   90,   90,   90,   90,   90,
       90,   90,   90,   90,   90,   90,   90,   90
    } ;

static wafsaconst short int wafsa_chk[139] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        5,    9,    9,   10,   16,    5,   12,   12,   10,   18,
       91,   16,   18,   21,   26,   21,   28,   28,   29,   26,
       52,   88,   52,   29,   85,   83,   82,   81,   80,   78,
       75,   73,   72,   71,   69,   68,   67,   66,   65,   64,
       63,   62,   61,   60,   59,   58,   57,   56,   55,   54,
       53,   50,   48,   46,   45,   44,   43,   42,   41,   40,
       39,   38,   37,   36,   35,   34,   33,   32,   31,   27,

       22,   20,   19,   17,   15,   11,    3,   90,   90,   90,
       90,   90,   90,   90,   90,   90,   90,   90,   90,   90,
       90,   90,   90,   90,   90,   90,   90,   90,   90,   90,
       90,   90,   90,   90,   90,   90,   90,   90
    } ;

static wafsa_state_type wafsa_last_accepting_state;
static char *wafsa_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define wafsamore() wafsamore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *wafsatext;
#line 1 "./fsaparse.l"
#define INITIAL 0
#line 2 "./fsaparse.l"

/*
 * fsaparse.l (lex.wafsa.c)
 *
 * Lex definitions for lexical scanner for parsing word-acceptor
 * automata.  See fsaparse.y for more info.
 *
 * mbp Sat Mar 23 21:58:12 1991
 * mbp@thales.urich.edu
 */

#include <stdio.h>
#include <stdlib.h> /* for atof() */
#include <math.h>
#include "yystype.h"
#include "y.tab.h"

extern YYSTYPE wafsalval;

/* disable output of unmatched input */
#undef output
#define output(c) 

#line 445 "lex.wafsa.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int wafsawrap YY_PROTO(( void ));
#else
extern int wafsawrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void wafsaunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef wafsatext_ptr
static void wafsa_flex_strncpy YY_PROTO(( char *, wafsaconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int wafsa_flex_strlen YY_PROTO(( wafsaconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int wafsainput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int wafsa_start_stack_ptr = 0;
static int wafsa_start_stack_depth = 0;
static int *wafsa_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void wafsa_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void wafsa_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int wafsa_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( wafsatext, wafsaleng, 1, wafsaout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( wafsa_current_buffer->wafsa_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( wafsain )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( wafsain ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, wafsain )) == 0) \
		  && ferror( wafsain ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "wafsaterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef wafsaterminate
#define wafsaterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) wafsa_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int wafsalex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after wafsatext and wafsaleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register wafsa_state_type wafsa_current_state;
	register char *wafsa_cp = NULL, *wafsa_bp = NULL;
	register int wafsa_act;

#line 32 "./fsaparse.l"


#line 599 "lex.wafsa.c"

	if ( wafsa_init )
		{
		wafsa_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! wafsa_start )
			wafsa_start = 1;	/* first start state */

		if ( ! wafsain )
			wafsain = stdin;

		if ( ! wafsaout )
			wafsaout = stdout;

		if ( ! wafsa_current_buffer )
			wafsa_current_buffer =
				wafsa_create_buffer( wafsain, YY_BUF_SIZE );

		wafsa_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		wafsa_cp = wafsa_c_buf_p;

		/* Support of wafsatext. */
		*wafsa_cp = wafsa_hold_char;

		/* wafsa_bp points to the position in wafsa_ch_buf of the start of
		 * the current run.
		 */
		wafsa_bp = wafsa_cp;

		wafsa_current_state = wafsa_start;
wafsa_match:
		do
			{
			register YY_CHAR wafsa_c = wafsa_ec[YY_SC_TO_UI(*wafsa_cp)];
			if ( wafsa_accept[wafsa_current_state] )
				{
				wafsa_last_accepting_state = wafsa_current_state;
				wafsa_last_accepting_cpos = wafsa_cp;
				}
			while ( wafsa_chk[wafsa_base[wafsa_current_state] + wafsa_c] != wafsa_current_state )
				{
				wafsa_current_state = (int) wafsa_def[wafsa_current_state];
				if ( wafsa_current_state >= 91 )
					wafsa_c = wafsa_meta[(unsigned int) wafsa_c];
				}
			wafsa_current_state = wafsa_nxt[wafsa_base[wafsa_current_state] + (unsigned int) wafsa_c];
			++wafsa_cp;
			}
		while ( wafsa_base[wafsa_current_state] != 108 );

wafsa_find_action:
		wafsa_act = wafsa_accept[wafsa_current_state];
		if ( wafsa_act == 0 )
			{ /* have to back up */
			wafsa_cp = wafsa_last_accepting_cpos;
			wafsa_current_state = wafsa_last_accepting_state;
			wafsa_act = wafsa_accept[wafsa_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( wafsa_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*wafsa_cp = wafsa_hold_char;
			wafsa_cp = wafsa_last_accepting_cpos;
			wafsa_current_state = wafsa_last_accepting_state;
			goto wafsa_find_action;

case 1:
YY_RULE_SETUP
#line 34 "./fsaparse.l"
;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 36 "./fsaparse.l"
{ return(FORMAT);	}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 37 "./fsaparse.l"
{ return(FORMAT);	}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 38 "./fsaparse.l"
{ return(FSA);		}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 39 "./fsaparse.l"
{ return(STATES);	}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 40 "./fsaparse.l"
{ return(SYMBOLS);	}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 41 "./fsaparse.l"
{ return(BFS);		}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 42 "./fsaparse.l"
{ return(MIN);		}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 43 "./fsaparse.l"
{ return(VARIABLES);	}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 44 "./fsaparse.l"
{ return(ALPHABET);	}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 45 "./fsaparse.l"
{ return(START);	}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 46 "./fsaparse.l"
{ return(ATABLE);	}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 47 "./fsaparse.l"
{ return(INVERSES);	}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 48 "./fsaparse.l"
{ return(INV);		}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 50 "./fsaparse.l"
{ return(LEFT_BRACE);	}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 51 "./fsaparse.l"
{ return(RIGHT_BRACE);	}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 52 "./fsaparse.l"
{ return(LEFT_PAREN);	}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 53 "./fsaparse.l"
{ return(RIGHT_PAREN);	}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 54 "./fsaparse.l"
{ return(SEMICOLON);	}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 55 "./fsaparse.l"
{ return(PERCENT);	}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 56 "./fsaparse.l"
{ return(EQUAL);	}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 58 "./fsaparse.l"
{ wafsalval.i = atoi(wafsatext); return(INT);  }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 59 "./fsaparse.l"
{ wafsalval.d = atof(wafsatext); return(REAL); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 60 "./fsaparse.l"
{ wafsalval.d = atof(wafsatext); return(REAL); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 62 "./fsaparse.l"
{ strcpy(wafsalval.s, wafsatext); return(STRING); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 64 "./fsaparse.l"
ECHO;
	YY_BREAK
#line 812 "lex.wafsa.c"
case YY_STATE_EOF(INITIAL):
	wafsaterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int wafsa_amount_of_matched_text = (int) (wafsa_cp - wafsatext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*wafsa_cp = wafsa_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( wafsa_current_buffer->wafsa_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed wafsain at a new source and called
			 * wafsalex().  If so, then we have to assure
			 * consistency between wafsa_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			wafsa_n_chars = wafsa_current_buffer->wafsa_n_chars;
			wafsa_current_buffer->wafsa_input_file = wafsain;
			wafsa_current_buffer->wafsa_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for wafsa_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since wafsa_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( wafsa_c_buf_p <= &wafsa_current_buffer->wafsa_ch_buf[wafsa_n_chars] )
			{ /* This was really a NUL. */
			wafsa_state_type wafsa_next_state;

			wafsa_c_buf_p = wafsatext_ptr + wafsa_amount_of_matched_text;

			wafsa_current_state = wafsa_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * wafsa_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			wafsa_next_state = wafsa_try_NUL_trans( wafsa_current_state );

			wafsa_bp = wafsatext_ptr + YY_MORE_ADJ;

			if ( wafsa_next_state )
				{
				/* Consume the NUL. */
				wafsa_cp = ++wafsa_c_buf_p;
				wafsa_current_state = wafsa_next_state;
				goto wafsa_match;
				}

			else
				{
				wafsa_cp = wafsa_c_buf_p;
				goto wafsa_find_action;
				}
			}

		else switch ( wafsa_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				wafsa_did_buffer_switch_on_eof = 0;

				if ( wafsawrap() )
					{
					/* Note: because we've taken care in
					 * wafsa_get_next_buffer() to have set up
					 * wafsatext, we can now set up
					 * wafsa_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					wafsa_c_buf_p = wafsatext_ptr + YY_MORE_ADJ;

					wafsa_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! wafsa_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				wafsa_c_buf_p =
					wafsatext_ptr + wafsa_amount_of_matched_text;

				wafsa_current_state = wafsa_get_previous_state();

				wafsa_cp = wafsa_c_buf_p;
				wafsa_bp = wafsatext_ptr + YY_MORE_ADJ;
				goto wafsa_match;

			case EOB_ACT_LAST_MATCH:
				wafsa_c_buf_p =
				&wafsa_current_buffer->wafsa_ch_buf[wafsa_n_chars];

				wafsa_current_state = wafsa_get_previous_state();

				wafsa_cp = wafsa_c_buf_p;
				wafsa_bp = wafsatext_ptr + YY_MORE_ADJ;
				goto wafsa_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of wafsalex */


/* wafsa_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int wafsa_get_next_buffer()
	{
	register char *dest = wafsa_current_buffer->wafsa_ch_buf;
	register char *source = wafsatext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( wafsa_c_buf_p > &wafsa_current_buffer->wafsa_ch_buf[wafsa_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( wafsa_current_buffer->wafsa_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( wafsa_c_buf_p - wafsatext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (wafsa_c_buf_p - wafsatext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( wafsa_current_buffer->wafsa_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		wafsa_current_buffer->wafsa_n_chars = wafsa_n_chars = 0;

	else
		{
		int num_to_read =
			wafsa_current_buffer->wafsa_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = wafsa_current_buffer;

			int wafsa_c_buf_p_offset =
				(int) (wafsa_c_buf_p - b->wafsa_ch_buf);

			if ( b->wafsa_is_our_buffer )
				{
				int new_size = b->wafsa_buf_size * 2;

				if ( new_size <= 0 )
					b->wafsa_buf_size += b->wafsa_buf_size / 8;
				else
					b->wafsa_buf_size *= 2;

				b->wafsa_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					wafsa_flex_realloc( (void *) b->wafsa_ch_buf,
							 b->wafsa_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->wafsa_ch_buf = 0;

			if ( ! b->wafsa_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			wafsa_c_buf_p = &b->wafsa_ch_buf[wafsa_c_buf_p_offset];

			num_to_read = wafsa_current_buffer->wafsa_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&wafsa_current_buffer->wafsa_ch_buf[number_to_move]),
			wafsa_n_chars, num_to_read );

		wafsa_current_buffer->wafsa_n_chars = wafsa_n_chars;
		}

	if ( wafsa_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			wafsarestart( wafsain );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			wafsa_current_buffer->wafsa_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	wafsa_n_chars += number_to_move;
	wafsa_current_buffer->wafsa_ch_buf[wafsa_n_chars] = YY_END_OF_BUFFER_CHAR;
	wafsa_current_buffer->wafsa_ch_buf[wafsa_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	wafsatext_ptr = &wafsa_current_buffer->wafsa_ch_buf[0];

	return ret_val;
	}


/* wafsa_get_previous_state - get the state just before the EOB char was reached */

static wafsa_state_type wafsa_get_previous_state()
	{
	register wafsa_state_type wafsa_current_state;
	register char *wafsa_cp;

	wafsa_current_state = wafsa_start;

	for ( wafsa_cp = wafsatext_ptr + YY_MORE_ADJ; wafsa_cp < wafsa_c_buf_p; ++wafsa_cp )
		{
		register YY_CHAR wafsa_c = (*wafsa_cp ? wafsa_ec[YY_SC_TO_UI(*wafsa_cp)] : 1);
		if ( wafsa_accept[wafsa_current_state] )
			{
			wafsa_last_accepting_state = wafsa_current_state;
			wafsa_last_accepting_cpos = wafsa_cp;
			}
		while ( wafsa_chk[wafsa_base[wafsa_current_state] + wafsa_c] != wafsa_current_state )
			{
			wafsa_current_state = (int) wafsa_def[wafsa_current_state];
			if ( wafsa_current_state >= 91 )
				wafsa_c = wafsa_meta[(unsigned int) wafsa_c];
			}
		wafsa_current_state = wafsa_nxt[wafsa_base[wafsa_current_state] + (unsigned int) wafsa_c];
		}

	return wafsa_current_state;
	}


/* wafsa_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = wafsa_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static wafsa_state_type wafsa_try_NUL_trans( wafsa_state_type wafsa_current_state )
#else
static wafsa_state_type wafsa_try_NUL_trans( wafsa_current_state )
wafsa_state_type wafsa_current_state;
#endif
	{
	register int wafsa_is_jam;
	register char *wafsa_cp = wafsa_c_buf_p;

	register YY_CHAR wafsa_c = 1;
	if ( wafsa_accept[wafsa_current_state] )
		{
		wafsa_last_accepting_state = wafsa_current_state;
		wafsa_last_accepting_cpos = wafsa_cp;
		}
	while ( wafsa_chk[wafsa_base[wafsa_current_state] + wafsa_c] != wafsa_current_state )
		{
		wafsa_current_state = (int) wafsa_def[wafsa_current_state];
		if ( wafsa_current_state >= 91 )
			wafsa_c = wafsa_meta[(unsigned int) wafsa_c];
		}
	wafsa_current_state = wafsa_nxt[wafsa_base[wafsa_current_state] + (unsigned int) wafsa_c];
	wafsa_is_jam = (wafsa_current_state == 90);

	return wafsa_is_jam ? 0 : wafsa_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void wafsaunput( int c, register char *wafsa_bp )
#else
static void wafsaunput( c, wafsa_bp )
int c;
register char *wafsa_bp;
#endif
	{
	register char *wafsa_cp = wafsa_c_buf_p;

	/* undo effects of setting up wafsatext */
	*wafsa_cp = wafsa_hold_char;

	if ( wafsa_cp < wafsa_current_buffer->wafsa_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = wafsa_n_chars + 2;
		register char *dest = &wafsa_current_buffer->wafsa_ch_buf[
					wafsa_current_buffer->wafsa_buf_size + 2];
		register char *source =
				&wafsa_current_buffer->wafsa_ch_buf[number_to_move];

		while ( source > wafsa_current_buffer->wafsa_ch_buf )
			*--dest = *--source;

		wafsa_cp += (int) (dest - source);
		wafsa_bp += (int) (dest - source);
		wafsa_current_buffer->wafsa_n_chars =
			wafsa_n_chars = wafsa_current_buffer->wafsa_buf_size;

		if ( wafsa_cp < wafsa_current_buffer->wafsa_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--wafsa_cp = (char) c;


	wafsatext_ptr = wafsa_bp;
	wafsa_hold_char = *wafsa_cp;
	wafsa_c_buf_p = wafsa_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int wafsainput()
#else
static int input()
#endif
	{
	int c;

	*wafsa_c_buf_p = wafsa_hold_char;

	if ( *wafsa_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* wafsa_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( wafsa_c_buf_p < &wafsa_current_buffer->wafsa_ch_buf[wafsa_n_chars] )
			/* This was really a NUL. */
			*wafsa_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = wafsa_c_buf_p - wafsatext_ptr;
			++wafsa_c_buf_p;

			switch ( wafsa_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because wafsa_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					wafsarestart( wafsain );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( wafsawrap() )
						return EOF;

					if ( ! wafsa_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return wafsainput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					wafsa_c_buf_p = wafsatext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) wafsa_c_buf_p;	/* cast for 8-bit char's */
	*wafsa_c_buf_p = '\0';	/* preserve wafsatext */
	wafsa_hold_char = *++wafsa_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void wafsarestart( FILE *input_file )
#else
void wafsarestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! wafsa_current_buffer )
		wafsa_current_buffer = wafsa_create_buffer( wafsain, YY_BUF_SIZE );

	wafsa_init_buffer( wafsa_current_buffer, input_file );
	wafsa_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void wafsa_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void wafsa_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( wafsa_current_buffer == new_buffer )
		return;

	if ( wafsa_current_buffer )
		{
		/* Flush out information for old buffer. */
		*wafsa_c_buf_p = wafsa_hold_char;
		wafsa_current_buffer->wafsa_buf_pos = wafsa_c_buf_p;
		wafsa_current_buffer->wafsa_n_chars = wafsa_n_chars;
		}

	wafsa_current_buffer = new_buffer;
	wafsa_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (wafsawrap()) processing, but the only time this flag
	 * is looked at is after wafsawrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	wafsa_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void wafsa_load_buffer_state( void )
#else
void wafsa_load_buffer_state()
#endif
	{
	wafsa_n_chars = wafsa_current_buffer->wafsa_n_chars;
	wafsatext_ptr = wafsa_c_buf_p = wafsa_current_buffer->wafsa_buf_pos;
	wafsain = wafsa_current_buffer->wafsa_input_file;
	wafsa_hold_char = *wafsa_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE wafsa_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE wafsa_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) wafsa_flex_alloc( sizeof( struct wafsa_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in wafsa_create_buffer()" );

	b->wafsa_buf_size = size;

	/* wafsa_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->wafsa_ch_buf = (char *) wafsa_flex_alloc( b->wafsa_buf_size + 2 );
	if ( ! b->wafsa_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in wafsa_create_buffer()" );

	b->wafsa_is_our_buffer = 1;

	wafsa_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void wafsa_delete_buffer( YY_BUFFER_STATE b )
#else
void wafsa_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == wafsa_current_buffer )
		wafsa_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->wafsa_is_our_buffer )
		wafsa_flex_free( (void *) b->wafsa_ch_buf );

	wafsa_flex_free( (void *) b );
	}



#ifdef YY_USE_PROTOS
void wafsa_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void wafsa_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	wafsa_flush_buffer( b );

	b->wafsa_input_file = file;
	b->wafsa_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->wafsa_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->wafsa_is_interactive = 0;
#else
	b->wafsa_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void wafsa_flush_buffer( YY_BUFFER_STATE b )
#else
void wafsa_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->wafsa_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->wafsa_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->wafsa_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->wafsa_buf_pos = &b->wafsa_ch_buf[0];

	b->wafsa_at_bol = 1;
	b->wafsa_buffer_status = YY_BUFFER_NEW;

	if ( b == wafsa_current_buffer )
		wafsa_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE wafsa_scan_buffer( char *base, wafsa_size_t size )
#else
YY_BUFFER_STATE wafsa_scan_buffer( base, size )
char *base;
wafsa_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) wafsa_flex_alloc( sizeof( struct wafsa_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in wafsa_scan_buffer()" );

	b->wafsa_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->wafsa_buf_pos = b->wafsa_ch_buf = base;
	b->wafsa_is_our_buffer = 0;
	b->wafsa_input_file = 0;
	b->wafsa_n_chars = b->wafsa_buf_size;
	b->wafsa_is_interactive = 0;
	b->wafsa_at_bol = 1;
	b->wafsa_fill_buffer = 0;
	b->wafsa_buffer_status = YY_BUFFER_NEW;

	wafsa_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE wafsa_scan_string( wafsaconst char *wafsa_str )
#else
YY_BUFFER_STATE wafsa_scan_string( wafsa_str )
wafsaconst char *wafsa_str;
#endif
	{
	int len;
	for ( len = 0; wafsa_str[len]; ++len )
		;

	return wafsa_scan_bytes( wafsa_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE wafsa_scan_bytes( wafsaconst char *bytes, int len )
#else
YY_BUFFER_STATE wafsa_scan_bytes( bytes, len )
wafsaconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	wafsa_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) wafsa_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in wafsa_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = wafsa_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in wafsa_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->wafsa_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void wafsa_push_state( int new_state )
#else
static void wafsa_push_state( new_state )
int new_state;
#endif
	{
	if ( wafsa_start_stack_ptr >= wafsa_start_stack_depth )
		{
		wafsa_size_t new_size;

		wafsa_start_stack_depth += YY_START_STACK_INCR;
		new_size = wafsa_start_stack_depth * sizeof( int );

		if ( ! wafsa_start_stack )
			wafsa_start_stack = (int *) wafsa_flex_alloc( new_size );

		else
			wafsa_start_stack = (int *) wafsa_flex_realloc(
					(void *) wafsa_start_stack, new_size );

		if ( ! wafsa_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	wafsa_start_stack[wafsa_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void wafsa_pop_state()
	{
	if ( --wafsa_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(wafsa_start_stack[wafsa_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int wafsa_top_state()
	{
	return wafsa_start_stack[wafsa_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void wafsa_fatal_error( wafsaconst char msg[] )
#else
static void wafsa_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine wafsaless() so it works in section 3 code. */

#undef wafsaless
#define wafsaless(n) \
	do \
		{ \
		/* Undo effects of setting up wafsatext. */ \
		wafsatext[wafsaleng] = wafsa_hold_char; \
		wafsa_c_buf_p = wafsatext + n; \
		wafsa_hold_char = *wafsa_c_buf_p; \
		*wafsa_c_buf_p = '\0'; \
		wafsaleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef wafsatext_ptr
#ifdef YY_USE_PROTOS
static void wafsa_flex_strncpy( char *s1, wafsaconst char *s2, int n )
#else
static void wafsa_flex_strncpy( s1, s2, n )
char *s1;
wafsaconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int wafsa_flex_strlen( wafsaconst char *s )
#else
static int wafsa_flex_strlen( s )
wafsaconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *wafsa_flex_alloc( wafsa_size_t size )
#else
static void *wafsa_flex_alloc( size )
wafsa_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *wafsa_flex_realloc( void *ptr, wafsa_size_t size )
#else
static void *wafsa_flex_realloc( ptr, size )
void *ptr;
wafsa_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void wafsa_flex_free( void *ptr )
#else
static void wafsa_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	wafsalex();
	return 0;
	}
#endif
#line 64 "./fsaparse.l"


wafsawrap()
{
  return(1);
}
