LObject * l_quote(LObject * a1);
void l_if(LObject * a1, LObject * a2, LObject * a3);
int l_greater(LObject * a1, LObject * a2);
int l_less(LObject * a1, LObject * a2);
int l_equal(LObject * a1, LObject * a2);
int l_sgi();
int l_NeXT();
LObject * l_progn(LList * a1);
LObject * l_car(LList  * a1);
LObject * l_cdr(LList  * a1);
void l_interest(LList  * a1);
void l_uninterest(LList  * a1);
void l_time_interests(float a1, char * a2, char * a3, char * a4);
void l_regtable();
void l_help(char * a1);
void l_morehelp(char * a1);
